version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: ..
      dockerfile: Api/Dockerfile

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.93.0
    container_name: otel-col
    command: [ "--config=/etc/otelcol-config.yml" ]
    volumes:
      - ../otel-collector/otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
